export const API_ERROR_TYPE = "API_Error";
export const API_APP_ERROR_MESSAGE = "APPLICATION ERROR";
export const API_EXPIERED_ERROR_MESSAGE = "DEADLINE_HAS_EXPIRED_ERROR";
export const API_HTTP_ERROR_MESSAGE = "HTTP_ERROR";
export const API_NO_OPENAPI_SERVICE_ERROR_MESSAGE = "NO_OPENAPI_SERVICE_ERROR";
export const API_EXCEEDS_ERROR_MESSAGE =
  "LIMITED_NUMBER_OF_SERVICE_REQUESTS_EXCEEDS_ERROR";
export const API_ACCESS_DENIED_ERROR_MESSAGE = "SERVICE_ACCESS_DENIED_ERROR";
export const API_KEY_IS_NOT_REGISTERED_ERROR_MESSAGE =
  "SERVICE_KEY_IS_NOT_REGISTERED_ERROR";
export const API_UNKNOWN_ERROR_MESSAGE = "UNKNOWN_ERROR";
export const API_UNREGISTERED_IP_ERROR_MESSAGE = "UNREGISTERED_IP_ERROR";
